version: '3.8'
services:
  fastapi:
    build: .
    command: ["poetry", "run", "uvicorn", "yt_rag.api.app:app", "--host", "0.0.0.0", "--port", "5000", "--log-config", "log_config.yml"]
    ports:
      - 5000:5000
    environment:
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
  streamlit:
    build: .
    command: ["poetry", "run", "streamlit", "run", "app.py"]
    container_name: streamlit
    ports:
      - 8501:8501
    depends_on:
      - fastapi
    environment:
      - API_ENDPOINT=http://fastapi:5000/rag
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
